### ISSUE TITLE
Document compilation

### ISSUE THREAD

**Issue by kanigsson** [HeisenbugLtd/spat#5]
Hello,

Unless I missed it, the project doesn't contain any info to build the executable. I tried
```
$ gprbuild -P spat
spat.gpr:2:06: unknown project file: "si_units_lib"
gprbuild: "spat" processing failed
```
I discovered the SI_Units project in your github profile, so I will go download that now ...

**Comment by Jellix** [comment]
Yes, indeed, I was planning to write up something before creating some kind of official release, it's all still WIP. :relaxed:

After cloning, doing gprinstall for si_units_lib should do the trick.

**Comment by kanigsson** [comment]
Looking forward to it :-) Got it compiled btw.

**Comment by Jellix** [comment]
README has been updated to provide installation instructions.
